name: new_version
description: Check if your user has the most recent version of your Flutter app.
version: 0.0.5
homepage: https://github.com/timtraversy/new_version

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  package_info: ^0.4.3
  http: ^0.12.2
  html: ^0.14.0+3
  url_launcher: ^5.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
